openapi: 3.0.1
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'https://api.example.com'
paths:
  /:
    get:
      summary: Returns a simple message to test if the server is online
      description: Optional extended description in Markdown.
      responses:
        '200':
          description: OK
